using System;
using System.Reflection;
using TMPro;
using UIKit.Components;
using UnityEngine;
using UnityEngine.UI;

namespace UIKit
{
    public class InputFieldView : View, IComponentAction<string>, IComponentActionSetup
    {
        private AInputField _inputField = default;

        private Action<string> _autoGeneratedAction = default;

        public string text
        {
            get => _inputField.text;
            set => _inputField.text = value;
        }

        #region Life cycle

        protected override void Awake()
        {
            base.Awake();
            
            TMP_InputField tmpInputField = GetComponent<TMP_InputField>();
            if (tmpInputField)
            {
                _inputField = new InputFieldTMP(tmpInputField);
                
                BindAction();

                return;
            }

            InputField inputField = GetComponent<InputField>();
            if (inputField)
            {
                _inputField = new InputFieldUI(inputField);
                
                BindAction();

                return;
            }

            throw new MissingComponentException($"Missing TMP_InputField or UI.InputField component.");
        }

        private void OnDestroy()
        {
            if (_inputField == null) return;

            _inputField.Clear();
            _inputField.onEndEditing -= _autoGeneratedAction;
        }

        #endregion

        #region IComponentAction<string>

        event Action<string> IComponentAction<string>.action
        {
            add => _inputField.onEndEditing += value;
            remove => _inputField.onEndEditing -= value;
        }

        #endregion

        #region IComponentActionSetup

        void IComponentActionSetup.SetupAction(UnityEngine.Object target, MethodInfo info)
        {
            _autoGeneratedAction = (Action<string>)info.CreateDelegate(typeof(Action<string>), target);

            BindAction();
        }

        #endregion

        private void BindAction()
        {
            if (_inputField == null) return;

            _inputField.onEndEditing -= _autoGeneratedAction;
            _inputField.onEndEditing += _autoGeneratedAction;
        }
    }
}
