using System;
using System.Reflection;
using TMPro;
using UIKit.Components;
using UnityEngine;
using UnityEngine.UI;

namespace UIKit
{
    public class DropdownView : View, IComponentAction<DropdownOption>, IComponentActionSetup
    {
        [SerializeField] private DropdownOption[] _startOptions = default;

        private ADropdown _dropdown = default;
        private Action<DropdownOption> _autoGeneratedAction = default;

        public event Action<DropdownOption> valueDidChange
        {
            add => _dropdown.valueDidChange += value;
            remove => _dropdown.valueDidChange -= value;
        }

        public void SetOptions(DropdownOption[] options) => _dropdown.SetOptions(options);

        protected override void Awake()
        {
            base.Awake();

            TMP_Dropdown tmpDropdown = GetComponent<TMP_Dropdown>();
            if (tmpDropdown)
            {
                _dropdown = new DropdownTMP(tmpDropdown);
                _dropdown.SetOptions(_startOptions);

                BindAction();

                return;
            }

            Dropdown dropdown = GetComponent<Dropdown>();
            if (dropdown)
            {
                _dropdown = new DropdownUI(dropdown);
                _dropdown.SetOptions(_startOptions);

                BindAction();

                return;
            }

            throw new MissingComponentException($"Missing TMP_Dropdown or UI.Dropdown component.");
        }

        private void OnDestroy()
        {
            if (_dropdown == null) return;

            _dropdown.Clear();
            _dropdown.valueDidChange -= _autoGeneratedAction;
        }

        #region IComponentAction<ADropdownOption>

        event Action<DropdownOption> IComponentAction<DropdownOption>.action
        {
            add => valueDidChange += value;
            remove => valueDidChange -= value;
        }

        #endregion

        #region IComponentActionSetup

        void IComponentActionSetup.SetupAction(UnityEngine.Object target, MethodInfo info)
        {
            _autoGeneratedAction = (Action<DropdownOption>)info.CreateDelegate(typeof(Action<DropdownOption>), target);

            BindAction();
        }

        #endregion
        
        private void BindAction()
        {
            if (_dropdown == null) return;

            _dropdown.valueDidChange -= _autoGeneratedAction;
            _dropdown.valueDidChange += _autoGeneratedAction;
        }
    }
}