using System;
using System.Reflection;
using UIKit.Components;
using UnityEngine;
using UnityEngine.UI;

namespace UIKit
{
    [RequireComponent(typeof(Button))]
    public class ButtonView : View, IComponentAction, IComponentActionSetup
    {
        private Button _button = default;
        private Action _autoGeneratedAction = default;

        public event Action onButtonAction;

        #region Life cycle

        protected override void Awake()
        {
            base.Awake();

            _button = GetComponent<Button>();
            _button.onClick.AddListener(InvokeAction);

            BindAction();
        }

        private void OnDestroy()
        {
            if (!_button) return;

            _button.onClick.RemoveAllListeners();
            onButtonAction -= _autoGeneratedAction;
        }

        #endregion

        #region IComponentAction

        event Action IComponentAction.action
        {
            add => onButtonAction += value;
            remove => onButtonAction -= value;
        }

        #endregion

        #region IComponentActionSetup

        void IComponentActionSetup.SetupAction(UnityEngine.Object target, MethodInfo info)
        {
            _autoGeneratedAction = (Action)info.CreateDelegate(typeof(Action), target);
            
            BindAction();
        }

        #endregion

        private void InvokeAction() => onButtonAction?.Invoke();

        private void BindAction()
        {
            if (!_button) return;

            onButtonAction -= _autoGeneratedAction;
            onButtonAction += _autoGeneratedAction;
        }
    }
}
